"""Reproduce the explicit-citation document sweep and validate review coverage.

Legal assessments live in coding/reg_e_clause_review.json. This script does not
infer legal labels. It verifies that every substantive line in every retrieved
document has a disposition, attaches exact text and hashes, and reports counts.
"""
import collections
import csv
import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / 'vendor/tau2-bench/data/tau2/domains/banking_knowledge/documents'
PATTERN = r'\breg(?:ulation)?\.?\s*e\b|\b1005\.'
ALIASES = {
    'bank_031': 'doc_bank_accounts_bank_accounts_(general)_031',
    'bank_032': 'doc_bank_accounts_bank_accounts_(general)_032',
    'bank_037': 'doc_bank_accounts_bank_accounts_(general)_037',
    'checking_006': 'doc_checking_accounts_checking_accounts_(general)_006',
}
LABELS = {'restrictive': 'Less protection', 'generous': 'More protection',
          'aligned': 'Consistent', 'uncertain': 'Conditional or unclear',
          'operational': 'Operational', 'context': 'Context'}

def main():
    files = sorted(DOCS.glob('*.json'))
    expected_hashes = {x['path']:x['sha256'] for x in json.loads((ROOT/'data/corpus_manifest.json').read_text())}
    screen, selected = [], {}
    for path in files:
        assert hashlib.sha256(path.read_bytes()).hexdigest() == expected_hashes['documents/'+path.name], path
        d = json.loads(path.read_text())
        hit = bool(re.search(PATTERN, d['title']+'\n'+d['content'], re.I))
        screen.append({'document': d['id'], 'title': d['title'], 'selected': hit,
                       'sha256': hashlib.sha256(path.read_bytes()).hexdigest()})
        if hit:
            selected[d['id']] = d
    assert set(selected) == set(ALIASES.values()), 'Citation matches changed. Review new documents.'
    review = json.loads((ROOT / 'coding/reg_e_clause_review.json').read_text())
    units = review['units']
    coverage = collections.defaultdict(set)
    for u in units:
        doc = selected[ALIASES[u['document']]]
        a,b = u['lines']
        assert 1 <= a <= b <= len(doc['content'].splitlines())
        u['source_document'] = doc['id']
        u['source_text'] = '\n'.join(doc['content'].splitlines()[a-1:b])
        u['source_url'] = 'https://github.com/sierra-research/tau2-bench/blob/fc0055dc4e0a316c3f83133267fbd6faaa770992/data/tau2/domains/banking_knowledge/documents/'+doc['id']+'.json'
        coverage[doc['id']].update(range(a,b+1))
    unreviewed, headings = [], []
    for name,d in selected.items():
        for n,line in enumerate(d['content'].splitlines(),1):
            if not line.strip() or n in coverage[name]:
                continue
            if line.startswith(('##','**')) or (name.endswith('_032') and n==24):
                headings.append({'document':name,'line':n,'text':line})
            else:
                unreviewed.append({'document':name,'line':n,'text':line})
    assert not unreviewed, unreviewed
    counts = dict(collections.Counter(u['direction'] for u in units))
    result = {'review_date':review['review_date'],'search_pattern':PATTERN,
              'documents_screened':len(files),'documents_selected':len(selected),
              'unit_rule':review['unit_rule'], 'classification_rule':review['classification_rule'], 'unit_count':len(units),'counts':counts,
              'coverage':'Every nonempty line has a reviewed unit or a heading disposition.',
              'headings':headings,'screen':screen,'units':units,
              'limitations':['One analyst with model assistance. No independent coding or legal expert review.',
              'Explicit citations define the retrieval boundary. This is not every policy potentially governed by Regulation E.',
              'Post hoc extension after the selected-case study. No new public-agent runs or new alternative grading predicates.',
              'Counts are clause occurrences. Repetition and unit boundaries prevent interpreting them as independent error rates.']}
    (ROOT/'results/reg_e_clause_audit.json').write_text(json.dumps(result,indent=2)+'\n')
    fields=['id','document','title','direction','legal_pinpoint','assessment','source_text','source_url']
    with (ROOT/'coding/reg_e_clause_ledger.csv').open('w',newline='') as f:
        w=csv.DictWriter(f,fieldnames=fields,extrasaction='ignore');w.writeheader();w.writerows(units)
    tex=['% Generated by scripts/audit_reg_e_clauses.py',r'\begin{table}[!htbp]',r'\centering\small',r'\begin{tabular}{lr}',r'\toprule Comparison with the legal rule & Clause occurrences\\',r'\midrule']
    for k in ['restrictive','generous','aligned','uncertain','operational','context']:
        tex.append(f'{LABELS[k]} & {counts.get(k,0)}'+r'\\')
    tex += [r'\bottomrule',r'\end{tabular}',r'\caption{A complete review of the four documents that explicitly cite Regulation E. Counts describe the units in the published ledger, including repeated rules. They do not estimate a benchmark-wide error rate. Operational units cover interface and security procedures.}',r'\label{tab:clause-counts}',r'\end{table}']
    (ROOT/'paper/generated/clause_counts.tex').write_text('\n'.join(tex)+'\n')
    print(json.dumps({'documents':len(files),'selected':len(selected),'units':len(units),'counts':counts}))

if __name__ == '__main__':
    main()
